class Strings{
   static String naturePollution='Nature de pollution';
   static String pollutionDefinition='La pollution est la dégradation ou l\'altération de l\'environnement,gé,eralemnt associée aux activités humaines par la diffusion direct ou indirecte de substances chimiques, physique ou biologique potentitillement toxique pour les organismes vivant ou qui interfèrent plus au moins avec les fonction naturalles des écosystèmes.Outre son impact sur la santé humaine et animale, il peut entraîner la migration ou l\'extinction de certaines espèces qui ne peuvent s\'adapter aux modifiaction de leur milieu naturel';
   static String recyclageDefinition = 'Le recyclage est un processus qui consiste à traiter les déchets pour récupérer les matériaux qui peuvent être réutilisés dans la fabrication d\'autres produits, qu\'ils soient similaires ou différents. Cela permet de réduire la quantité de déchets qui finissent dans les sites d\'enfouissement, de diminuer la pollution environnementale et de préserver les ressources naturelles. En récupérant des matières premières déjà extraites, le recyclage permet également de limiter la consommation d\'énergie nécessaire à l\'extraction de nouvelles ressources. C\'est pourquoi le recyclage est considéré comme une solution essentielle pour assurer un développement durable et protéger notre environnement.';
   static String r_3_1 ='Le processus de recyclage implique plusieurs étapes, allant de la collecte des déchets jusqu\'à leur transformation en matières premières recyclées et leur utilisation dans la fabrication de nouveaux produits.\nPour encourager un mode de vie plus responsable, la notion des "3R" du recyclage est un guide utile pour réduire les déchets:';
   static String reduire ='la meilleure façon de recycler un déchet est de ne pas le produire en premier lieu.';
   static String reutiliser = 'donner une seconde vie aux objets plutôt que de les jeter permet de prolonger leur durée de vie et de réduire la quantité de déchets produits.';
   static String recycle = 'si les deux premières options ne sont pas possibles, il est important de recycler correctement les déchets en respectant les consignes de tri pour qu\'ils puissent être transformés en matières premières réutilisables.';
   static String triman ='Il est important de trier ou rapporter le produit à un point de collecte pour qu\'il puisse être recyclé. Il ne doit pas être jeté dans la poubelle ordinaire. Bien que certains produits recyclables ne portent pas encore l\'étiquette de tri, ils doivent quand même être triés.';
   static String triangledeMobius ='Même si le produit ou l\'emballage est techniquement recyclable, il ne sera effectivement recyclé que s\'il existe un système de collecte et une filière de recyclage disponibles dans votre région.';
   static String consignesIntroTri ='Une signalétique plus graphique est mise en place pour faciliter les consignes de tri. Elle détaille les matériaux à trier ou à jeter pour éviter toute confusion.';
   static String poubellebarree = 'Il est impératif de faire l\'objet d\'une collecte séparée pour les déchets provenant des produits électriques et électroniques ainsi que les piles. Ces déchets ne doivent pas être jetés dans les ordure ménagères.';
   static String pointVert = 'Le logo Point Vert peut être trompeur dans les consignes de tri. En réalité, ce logo indique seulement que l\'entreprise est partenaire du programme de valorisation des emballages ménagers et finance l\'organisation du tri sélectif. Il ne signifie pas que l\'emballage est recyclable ou qu\'il peut être mis dans la poubelle de tri.';
   static String tidyman='Le sigle Tidyman encourage simplement les consommateurs à jeter leur déchet dans une poubelle, sans donner d\'indication quant aux consignes de tri.';
   static String industrielDefinition="Les industries peuvent produire des émissions de gaz, de fumées, de poussières et de produits chimiques toxiques dans l'air et dans l'eau. Par exemple, les usines chimiques peuvent rejeter des produits toxiques tels que le mercure, le plomb et le cadmium dans les cours d'eau.";
   static String transportDefinition=" Les voitures, les camions, les avions et les bateaux produisent des gaz d'échappement qui peuvent être nocifs pour la santé humaine et l'environnement. Les émissions de dioxyde de carbone (CO2) contribuent également au changement climatique.";
   static String agricultureDefinition=" Les pesticides et les engrais chimiques utilisés dans l'agriculture peuvent contaminer l'eau et les sols. Les excréments d'animaux provenant des exploitations agricoles peuvent également contaminer les cours d'eau.";
   static String dechetsDefinition="Les déchets peuvent polluer l'environnement lorsqu'ils sont jetés de manière inappropriée. Les décharges peuvent libérer des produits chimiques toxiques dans le sol et les eaux souterraines. Les déchets alimentaires non compostés peuvent également produire du méthane, un gaz à effet de serre qui contribue au changement climatique.";
   static String domestiqueDefinition="Les produits chimiques utilisés dans les produits de nettoyage, les peintures et les solvants peuvent produire des émissions toxiques. Les déchets domestiques, tels que les piles, les appareils électroniques et les médicaments périmés, peuvent également contaminer l'environnement lorsqu'ils sont jetés de manière inappropriée";
}