class Strings{
   static String nature_Pollution='Nature de pollution';
   static String pollutionDefinition='La pollution est la dégradation ou l\'altération de l\'environnement,gé,eralemnt associée aux activités humaines par la diffusion direct ou indirecte de substances chimiques, physique ou biologique potentitillement toxique pour les organismes vivant ou qui interfèrent plus au moins avec les fonction naturalles des écosystèmes.Outre son impact sur la santé humaine et animale, il peut entraîner la migration ou l\'extinction de certaines espèces qui ne peuvent s\'adapter aux modifiaction de leur milieu naturel';
   static String recyclageDefinition = 'Le recyclage est un processus qui consiste à traiter les déchets pour récupérer les matériaux qui peuvent être réutilisés dans la fabrication d\'autres produits, qu\'ils soient similaires ou différents. Cela permet de réduire la quantité de déchets qui finissent dans les sites d\'enfouissement, de diminuer la pollution environnementale et de préserver les ressources naturelles. En récupérant des matières premières déjà extraites, le recyclage permet également de limiter la consommation d\'énergie nécessaire à l\'extraction de nouvelles ressources. C\'est pourquoi le recyclage est considéré comme une solution essentielle pour assurer un développement durable et protéger notre environnement.';
   static String r_3_1 ='Le processus de recyclage implique plusieurs étapes, allant de la collecte des déchets jusqu\'à leur transformation en matières premières recyclées et leur utilisation dans la fabrication de nouveaux produits.\nPour encourager un mode de vie plus responsable, la notion des "3R" du recyclage est un guide utile pour réduire les déchets:';
   static String reduire ='la meilleure façon de recycler un déchet est de ne pas le produire en premier lieu.';
   static String reutiliser = 'donner une seconde vie aux objets plutôt que de les jeter permet de prolonger leur durée de vie et de réduire la quantité de déchets produits.';
   static String recycle = 'si les deux premières options ne sont pas possibles, il est important de recycler correctement les déchets en respectant les consignes de tri pour qu\'ils puissent être transformés en matières premières réutilisables.';

}